Update FundMe.test.js
Change line 126 due to error:  
 AssertionError: Expected transaction to be reverted, but other exception was thrown: RangeError: Maximum call stack size exceeded

// Make a getter for storage variables
```
await expect(fundMe.getFunder(0)).to.be.reverted
```
Changed to 

```
await expect(fundMe.getFunder({ value: 0 })).to.be.reverted
```
This worked for me if this is correct syntax, it probably should be changed